// =============================================================================
// MINDI — Brain Link Generator
// Produces a static, read-only context snippet that can be pasted into
// any external AI (ChatGPT, Claude.ai, Gemini, etc.) to make it respond
// in the user's style using their knowledge.
//
// Trust Covenant:
//   - User selects which regions to include
//   - Time-limited by default (24h)
//   - One-click revocable from dashboard
//   - MFA required to create (enforced in API route)
//   - Encrypted node content NEVER included
// =============================================================================

import type { BrainNode, StyleFingerprint, NodeRegion } from '../../../../../shared/types';
import type { BrainLinkConfig, BrainLinkSnippet } from '../../../../../shared/types/phase2';
import { BRAIN_LINK_CONFIG, RISK_GATE } from '../../../../../shared/constants/phase2';
import { REGIONS } from '../../../../../shared/constants';

export function generateBrainLinkSnippet(
  nodes: BrainNode[],
  fingerprint: StyleFingerprint,
  config: BrainLinkConfig
): BrainLinkSnippet {
  // Filter: only selected regions, not encrypted, not archived
  const eligibleNodes = nodes
    .filter(
      (n) =>
        config.regions.includes(n.region) &&
        !n.isEncrypted &&
        !n.isArchived
    )
    .sort((a, b) => b.confidence - a.confidence) // Highest confidence first
    .slice(0, config.maxNodes);

  // --- Style section ---
  const styleSection = buildStyleSection(fingerprint, config.regions);

  // --- Knowledge section ---
  const knowledgeSection = buildKnowledgeSection(eligibleNodes);

  // --- Instruction section ---
  const instructionSection = buildInstructionSection(config.regions, fingerprint);

  const fullText = [
    BRAIN_LINK_CONFIG.INSTRUCTION_HEADER,
    styleSection,
    knowledgeSection,
    instructionSection,
  ].join('\n\n');

  // Trim to max chars
  const trimmed = fullText.slice(0, BRAIN_LINK_CONFIG.MAX_SNIPPET_CHARS);

  return {
    header: BRAIN_LINK_CONFIG.INSTRUCTION_HEADER,
    styleSection,
    knowledgeSection,
    instructionSection,
    fullText: trimmed,
    characterCount: trimmed.length,
    tokenEstimate: Math.ceil(trimmed.length / 4),
  };
}

function buildStyleSection(
  fingerprint: StyleFingerprint,
  regions: NodeRegion[]
): string {
  const overall = fingerprint.overall;
  if (!overall) return '';

  const lines = ['## My Writing & Communication Style'];

  if (overall.toneKeywords?.length) {
    lines.push(`**Tone**: ${overall.toneKeywords.join(', ')}`);
  }
  if (overall.vocabLevel) {
    lines.push(`**Vocabulary**: ${overall.vocabLevel}`);
  }
  if (overall.preferredStructure) {
    lines.push(`**Structure preference**: ${overall.preferredStructure}`);
  }
  if (overall.avgSentenceLength) {
    lines.push(`**Average sentence length**: ~${Math.round(overall.avgSentenceLength)} words`);
  }

  // Region-specific style overrides
  for (const region of regions) {
    const regionStyle = fingerprint.byRegion?.[region];
    if (regionStyle?.toneKeywords?.length) {
      lines.push(
        `**${REGIONS[region].label} style**: ${regionStyle.toneKeywords.join(', ')}`
      );
    }
  }

  return lines.join('\n');
}

function buildKnowledgeSection(nodes: BrainNode[]): string {
  if (nodes.length === 0) return '';

  const lines = ['## My Knowledge & Context'];

  for (const node of nodes) {
    const regionLabel = REGIONS[node.region]?.label ?? node.region;
    const excerpt = node.content.slice(0, 300).replace(/\n+/g, ' ').trim();
    lines.push(
      `**[${regionLabel}] ${node.title}** (${Math.round(node.confidence * 100)}% confidence)\n> ${excerpt}${node.content.length > 300 ? '…' : ''}`
    );
  }

  return lines.join('\n\n');
}

function buildInstructionSection(
  regions: NodeRegion[],
  fingerprint: StyleFingerprint
): string {
  const regionLabels = regions.map((r) => REGIONS[r].label).join(', ');
  const toneHint = fingerprint.overall?.toneKeywords?.slice(0, 3).join(', ') ?? 'clear and direct';

  return `## Instructions for AI
When responding to me, please:
1. Use the style described above — ${toneHint}
2. Reference my knowledge context where relevant
3. Match my preferred structure (${fingerprint.overall?.preferredStructure ?? 'mixed'})
4. This context covers my: ${regionLabels}
5. This Brain Link is read-only and was generated by Mindi.`;
}
