// =============================================================================
// MINDI — Phase 2 Constants
// Risk-based automation rules, proactivity config, voice settings.
// =============================================================================

import type { AutomationTaskType, RiskLevel } from '../types/phase2';

// -----------------------------------------------------------------------------
// RISK-BASED AUTOMATION RULES
// Every automation task type has a fixed risk level — non-negotiable.
// Trust Covenant: never auto-execute MEDIUM or HIGH without approval.
// -----------------------------------------------------------------------------

export const AUTOMATION_RISK_MAP: Record<AutomationTaskType, RiskLevel> = {
  // LOW — auto-execute, no approval needed
  summarize: 'LOW',

  // MEDIUM — show preview, require user click to accept
  homework_outline: 'MEDIUM',
  quiz_generate: 'MEDIUM',
  skill_gap_analysis: 'MEDIUM',
  review_feedback: 'MEDIUM',

  // HIGH — preview + explicit approve + MFA challenge
  homework_draft: 'HIGH',
  email_draft: 'HIGH',
};

export const RISK_GATE: Record<RiskLevel, {
  label: string;
  color: string;
  requiresPreview: boolean;
  requiresMfa: boolean;
  description: string;
}> = {
  LOW: {
    label: 'Auto',
    color: '#22c55e',
    requiresPreview: false,
    requiresMfa: false,
    description: 'Mindi executes automatically',
  },
  MEDIUM: {
    label: 'Preview',
    color: '#f59e0b',
    requiresPreview: true,
    requiresMfa: false,
    description: 'Review before accepting',
  },
  HIGH: {
    label: 'Approve',
    color: '#ef4444',
    requiresPreview: true,
    requiresMfa: true,
    description: 'Explicit approval + MFA required',
  },
};

// -----------------------------------------------------------------------------
// PROACTIVITY ENGINE CONFIG
// -----------------------------------------------------------------------------

export const PROACTIVITY_CONFIG = {
  // Minimum time between alerts of the same trigger type (ms)
  COOLDOWN_MS: {
    deadline_detected: 4 * 60 * 60 * 1000,   // 4 hours
    contradiction_found: 2 * 60 * 60 * 1000, // 2 hours
    skill_gap_detected: 24 * 60 * 60 * 1000, // 24 hours
    idle_suggestion: 30 * 60 * 1000,         // 30 minutes
    stress_detected: 15 * 60 * 1000,         // 15 minutes
    pattern_insight: 6 * 60 * 60 * 1000,     // 6 hours
  },

  // Stress detection thresholds
  STRESS: {
    LATE_HOUR_THRESHOLD: 23,   // 11 PM+
    REVISION_RATE_HIGH: 5,     // Edits per minute
    SESSION_LONG_MINUTES: 120, // 2+ hours = fatigue signal
  },

  // Idle suggestion: show ambient hint after X minutes of inactivity
  IDLE_MINUTES: 10,
} as const;

// -----------------------------------------------------------------------------
// VOICE PIPELINE CONFIG
// voice-agents skill: pipeline STT → LLM → TTS, budget latency per stage
// -----------------------------------------------------------------------------

export const VOICE_CONFIG = {
  // STT: Web Speech API (browser-native, zero latency overhead)
  STT_ENGINE: 'web-speech-api' as const,

  // TTS: Web Speech API for Phase 2 (Coqui XTTS in Phase 4)
  TTS_ENGINE: 'web-speech-api' as const,

  // Latency budget (voice-agents skill guidance)
  LATENCY_BUDGET_MS: {
    stt: 200,    // Streaming — near-instant
    llm: 1500,   // RAG + OpenRouter haiku-4
    tts: 300,    // Web Speech API synthesis
    total: 2000, // Target: under 2s end-to-end
  },

  // Wake word (client-side keyword detection)
  WAKE_WORD: 'hey mindi',

  // Max recording length before auto-stop
  MAX_RECORDING_MS: 30_000,

  // VAD silence threshold (ms of silence = end of utterance)
  VAD_SILENCE_MS: 1200,
} as const;

// -----------------------------------------------------------------------------
// BRAIN LINK CONFIG
// -----------------------------------------------------------------------------

export const BRAIN_LINK_CONFIG = {
  MAX_NODES_IN_SNIPPET: 10,
  MAX_SNIPPET_CHARS: 4000, // ~1000 tokens — fits in most AI context windows
  DEFAULT_EXPIRY_HOURS: 24,
  INSTRUCTION_HEADER: `# Mindi Brain Link
This context was generated by Mindi and belongs to its owner.
It is read-only and time-limited. Use it to respond in the owner's style and voice.
`,
} as const;

// -----------------------------------------------------------------------------
// EMOTIONAL STATE → UI ADAPTATION
// -----------------------------------------------------------------------------

export const EMOTIONAL_UI_ADAPTATION = {
  focused: {
    suggestionFrequency: 'low',
    orbOpacity: 0.15,
    transitionSpeed: 'fast',
  },
  stressed: {
    suggestionFrequency: 'none',
    orbOpacity: 0.08,
    transitionSpeed: 'slow',
    showCalmPrompt: true,
  },
  fatigued: {
    suggestionFrequency: 'none',
    orbOpacity: 0.06,
    transitionSpeed: 'slow',
    showBreakPrompt: true,
  },
  neutral: {
    suggestionFrequency: 'medium',
    orbOpacity: 0.2,
    transitionSpeed: 'base',
  },
  productive: {
    suggestionFrequency: 'medium',
    orbOpacity: 0.25,
    transitionSpeed: 'base',
  },
} as const;
